# Generated by Django 5.2.7 on 2025-10-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
