# Generated by Django 5.2.7 on 2025-10-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_alter_seat_seat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="section",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
