# Generated by Django 5.2.7 on 2025-10-13 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.PositiveIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("toss", "토스페이먼츠"),
                            ("kakao", "카카오페이"),
                            ("card", "신용카드"),
                            ("naver", "네이버페이"),
                        ],
                        default="toss",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "결제대기"),
                            ("completed", "결제완료"),
                            ("failed", "결제실패"),
                            ("cancelled", "결제취소"),
                            ("refunded", "환불완료"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("payment_time", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="match.match",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
