# Generated by Django 5.2.6 on 2025-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                (
                    "poster1",
                    models.ImageField(
                        blank=True,
                        default="posters/default.png",
                        null=True,
                        upload_to="posters/",
                    ),
                ),
                (
                    "poster2",
                    models.ImageField(
                        blank=True,
                        default="posters/default.png",
                        null=True,
                        upload_to="posters/",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
