# Generated by Django 5.2.6 on 2025-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="poster1",
            field=models.CharField(
                blank=True, default="posters/default.png", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="poster2",
            field=models.CharField(
                blank=True, default="posters/default.png", max_length=500, null=True
            ),
        ),
    ]
