# Generated by Django 5.2.6 on 2025-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_alter_match_poster1_alter_match_poster2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
