# Generated by Django 5.2.7 on 2025-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
